// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czmpkfbffysaeeiqwbao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bXBrZmJmZnlzYWVlaXF3YmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODQ5MjAsImV4cCI6MjA2ODY2MDkyMH0.zEH4dq-LXSRuMD-8xAWhkk0MkB-NE0-FZSGibrkH5H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});